from pygame import Color


SCREEN_WIDTH = 800
SCREEN_HEIGHT = 480
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
MENU_BG_COLOR = Color('#333377')
GAME_BG_COLOR = Color('#000077')

WALL_WIDTH = 32
WALL_HEIGHT = 32
WALL_SIZE = (WALL_WIDTH, WALL_HEIGHT)
WALL_COLOR = Color('#662218')

HUNTER_WIDTH = 32
HUNTER_HEIGHT = 32
HUNTER_SIZE = (HUNTER_WIDTH, HUNTER_HEIGHT)
HUNTER_SPEED = 5
HUNTER_COLOR = Color('#AAAAAA')

BTN_WIDTH = 200
BTN_HEIGHT = 80
BTN_SIZE = (BTN_WIDTH, BTN_HEIGHT)
BTN_TXT_USUAL_COLOR = Color('#FFFFFF')
BTN_TXT_SELECTED_COLOR = Color('#FF8888')
BTN_TXT_INACTIVE_COLOR = Color('#777777')
BTN_BG_COLOR = Color('#444466')
BTN_FONT_SIZE = 34

LBL_TXT_COLOR = Color('#FFFFFF')
LBL_FONT_SIZE = 20
